.dapprpc, .gitmodules, src/NFTPool.sol, src/Pool.sol, src/test/BaseTest.t.sol, src/test/NFTPool.t.sol, src/test/Pool.t.sol, src/test/User.t.sol
Here is my PR to support NFT streaming in the funding pool.
**Pool Contract**
- all internal methods have a underscore
- introduction of `address id` replace all internal usages of msg.sender with `id`
- kept all public view method interfaces which use msg.sender
- we can break the interface and require `address id` param or a separate method
- no proxy support for NFT because we want to remove it
**NFT Pool Contract**
- unique id based on the `keccak256(abi.encodePacked(nftRegistry, tokenId)` 
- collect and updateSender requires the NFT ownership
- we might should consider renaming the function to `updateNFTSender`
**Tests**
- added first basic tests for NFT streaming
- NFT to address streaming
- NFT to NFT streaming
- address to NFT streaming
- the old javascript tests are still …
=> feat: NFT support for Pool contract

src/NFTPool.sol, src/Pool.sol
Making the main pool methods (`updateSender, collect`) virtual allows to inherit from the Pool contract.
This enables to add custom streaming logic on top.
=> feat: virtual updateSender and collect

src/Pool.sol, src/test/Pool.t.sol, src/test/User.t.sol, src/test/UserUtils.t.sol
Depends on drips: https://github.com/radicle-dev/radicle-streaming/pull/33
Adds an escape hatch in case of too many collectable cycles to collect in a single transaction. Hopefully never used.
=> Add flushCycles

src/Pool.sol
Based on realization that `amtDeltas[cycleX].nextCycle` will never be updated when `cycleX` is finished. That means that when `cycleX` is collected, value of its `nextCycle` is final and can be safely consumed and deleted.
When a receiver has `amtDelta` set for the first time ever, let's say that for `cycleY`, `amtDeltas[cycleY].thisCycle` is set, never `amtDeltas[cycleY-1].nextCycle`, so the latter doesn't need to be ever analyzed.
This PR reduces two SLOADs to one for each collected cycle.
=> Cheap collect

src/DaiPool.sol, src/ERC20Pool.sol, src/EthPool.sol, src/Pool.sol, src/test/Pool.t.sol, src/test/User.t.sol, src/test/UserUtils.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/44.
This is a major shift in the pool API, drops the notion of weights in favor of plain amtPerSecs. This PR is divided into 2 commits and it's probably the best approach to view them one after another:
1. updates the logic and the tests in the most concise way
2. renames things and fixes comments without altering the logic
The gas usage of all calls to `updateSender` in all tests drops from 6,970,631 to 5,670,301 (19%).
=> Switch receivers configuration from weights to amtPerSec

src/Pool.sol, src/test/Pool.t.sol
A minor tweak to the drips splitting algorithm making it split cleanly, without the reminder. Previously the reminder was always sent to the receiver, even if dripping was set to 100%. This was wasting gas and potentially causing issues with contracts not expecting receiving transfers.
=> Split drips without reminder

src/ERC20Pool.sol, src/EthPool.sol, src/Pool.sol, src/test/Pool.t.sol, src/test/User.t.sol, src/test/UserUtils.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/52. This is the first PR for making the drips configuration independent from the sender's receivers list. It allows storing the drips receivers, but they aren't used anywhere yet.
=> Add setDripsReceiver

src/DaiPool.sol, src/ERC20Pool.sol, src/EthPool.sol, src/Pool.sol, src/test/Pool.t.sol, src/test/User.t.sol, src/test/UserUtils.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/53. Switches drips from using the senders' receivers lists to drips receivers lists. It's probably the best to review commit by commit, each of them is self-contained.
=> Use drips receivers

src/ERC20Pool.sol, src/EthPool.sol, src/Pool.sol
This allows removing some duplicate logic and clean up functions naming. It's a purely refactoring PR.
=> Use SenderId in internal functions

src/Pool.sol, src/test/Pool.t.sol, src/test/User.t.sol, src/test/UserUtils.t.sol
~Depends on https://github.com/radicle-dev/radicle-streaming/pull/59. Completes naming transition from `topUp` and `withdraw` to `sender balance`.~
~Now that I'm thinking about it, **maybe we should drop `withdrawable/senderBalance` entirely?** Without any on-chain sender state left it's nothing more than a simple helper, which takes the input parameters and does a few calculations on them. If there's a need to encapsulate the knowledge about how the pool works and e.g. how much is witdrawable, maybe we should create a library for other contracts? That'd be also cheaper to use without making full inter-contract calls.~
~I've pushed the second commit dropping `senderBalance`. It can be either squashed or reverted.~
Just drops `withdrawable`.
=> Drop withdrawable

src/DaiDripsHub.sol, src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol
Unfortunately `alias` is a solidity keyword :grimacing: IMO `account` is fine too.
=> Rename sub-sender to account

src/DripsHub.sol
Depends on https://github.com/radicle-dev/radicle-drips-hub/pull/69. Cuts gas of `_totalDripsAmtPerSec` by 60% or by ~17K for the maximum 100 receivers.
=> Optimize _totalDripsAmtPerSec

src/Dai.sol, src/DaiDripsHub.sol, src/DaiReserve.sol, src/ERC20DripsHub.sol, src/ERC20Reserve.sol, src/test/ERC20DripsHub.t.sol, src/test/TestDai.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/56.
It may make sense to require that the user of the hub approves spending of ERC-20 not by the hub itself, but by `hub.reserve()`. It'd save us an unnecessary transfer, but it could be weirder for the users of the hub.
=> Add ERC-20 reserve

src/DaiDripsHub.sol, src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/ManagedDripsHub.sol, src/test/DripsHubUser.t.sol, src/test/ERC20DripsHub.t.sol, src/test/EthDripsHub.t.sol
It puts all DripsHubs behind a proxy making them upgradable using the UUPS pattern.
Moves the owner and paused state to the unstructured storage. To do that the PR adds new mixins. The next PR #74 moves the rest of the DripsHub storage to unstructured storage. This way any upgrades in any part of the inheritance tree can be done atomically and without affecting the storage layout.
=> Add DripsHub proxy

src/DaiDripsHub.sol, src/ERC20DripsHub.sol, src/test/ERC20DripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/95.
The reserve doesn't need to be changeable on the drips hub side. With the introduction of the multi-token reserve it'll be not only unnecessary but also virtually impossible. The logic without the reserve setter is simpler and safer, also the gas cost for the users is lower because there are fewer storage accesses. This PR doesn't prevent the immutable variable from being changed with a logic upgrade.
CC: [deckardkrug](https://github.com/deckardkrug)
=> Make reserve immutable in hub

src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol, src/test/ManagedDripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/96, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/105.
Stops `setSplits` from collecting. Adds asset ID to events, as of now it's just `DUMMY_ASSET` and it's unindexed until we remove support for raw address user identity and free up indexed event slots.
The next step is to add the actual asset ID to the DripsHub API.
=> Almost multi-token DripsHub

src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/ManagedDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol, src/test/ManagedDripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/98, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/111.
Adds the notion of a `userId` composed of the `account` and `subAccount`. Replaces all usage of accounts (address + uint256) with the new userId (uint256). It's been used for the user identification only in 2 functions: in `setDrips` (only the sender) and `give` (only the giver).
Temporarily adds the special account 0, which allows controlling sub-account equal to `msg.sender` without account creation. This is needed so we can keep the old API implicitly using `msg.sender` to identify the users, e.g. in `function give(address receiver, uint128 amt)`. This special case can be dropped when we switch the whole API to `userId` and outsource the EOA API to a …
=> Replace user accounts with user IDs

src/DaiDripsHub.sol, src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol, src/test/ManagedDripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/98, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/112.
Switches the receiver configurations from addresses to user IDs for `setDrips`, `setSplits` and `give`. Now it's possible to support any sub-account, but only theoretically, there is still no way to collect for any sub-account, that'll be implemented in the upcoming PRs.
=> Receiver user IDs

src/DaiDripsHub.sol, src/DripsHub.sol, src/ERC20DripsHub.sol, src/EthDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol, src/test/EthDripsHub.t.sol, src/test/ManagedDripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/98, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/113.
Switches the sender identification from implicit msg.sender to user ID. This means an API change for `setSplits` and dropping of msg.sender versions of `setDrips` and `give`.
=> Sender user IDs

src/DripsHub.sol, src/ManagedDripsHub.sol, src/test/DripsHub.t.sol, src/test/DripsHubUser.t.sol, src/test/DripsHubUserUtils.t.sol, src/test/ManagedDripsHub.t.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/98, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/114.
Switches the collecting functions identification from implicit msg.sender to user ID. This means that sub-accounts can collect.
=> Collectors user IDs

src/DripsHub.sol, src/test/DripsHub.t.sol
Blocked by #119.
Account ownership transfer may be needed when upgrading identity contracts. Because the function is callable only by the account owner, it requires the identity contract to explicitly support that flow, it's an opt-in feature.
Also fixes missing account events.
=> Add account ownership transfer

src/Drips.sol, src/DripsHub.sol, src/Splits.sol, src/test/DripsHub.t.sol, src/test/ERC20DripsHub.t.sol
Blocked by #120.
Refactors Drips and Splits logic from DripsHub into libs. The libs have API directly copy-pasted from DripsHub API. Later we should polish it to make it more sensible for usage in other projects, e.g. make names more sensible, add extensive docs and tests hammering the libs directly.
=> Create rough libs

src/AddressId.sol, src/ERC20DripsHub.sol, src/ERC20Reserve.sol, src/test/ERC20Reserve.t.sol
This saves a `transfer` when moving tokens into or out of the drips contract.
=> Drop DripsHub from asset flow

src/AddressId.sol, src/DripsHub.sol, src/test/AddressIdUser.t.sol, src/test/DripsHub.t.sol, src/test/DripsHubUserUtils.t.sol
Blocked by #125 
Switches DripsHub API from requiring leakingly abstract assetIDs to plain IERC20 addresses.
=> Accept IERC20 in DripsHub API

src/Splits.sol, src/test/DripsHub.t.sol, src/test/Splits.t.sol
I migrated the splits tests from `DripsHub.t.sol` which only tests the Split library.
I modified some of them and changed the initial supply to a `give` instead of  `drip` if the test covers more split specific setups.
=> test: migrate splits tests to only test the library

src/Drips.sol, src/DripsHub.sol, src/test/Drips.t.sol
In the current code the max timestamp was lower than `type(uint64).max` only to cover an absurd edge case of cycle length of 1 second.
=> Remove drips artificial max timestamp

src/Drips.sol, src/DripsHub.sol, src/test/Drips.t.sol, src/test/DripsHub.t.sol, src/test/DripsHubUserUtils.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/128.
This PR reduces the maximum timestamp from uint64 to uint32 moving the death of drips protocol from year 584554532842 to mere 2106.  It allows storing on-chain the default drips end without using any additional slots.
=> Store the default drips end on-chain

src/DripsHub.sol, src/test/DripsHub.t.sol
Also moves 2 `collectAll` tests back to the place where similar tests are to make it easier to find them.
=> Make transferAccount pausable

src/AddressId.sol
Instead of copying `calldata -> memory -> memory` to make a call, we just copy `calldata -> memory`.
=> Make passthrough parameters calldata

src/Drips.sol, src/test/Drips.t.sol
This PR contains a new approach for calculating the `defaultEnd` based on an unsorted array.
All existing tests are passing and I added a couple more.
However, there might be still some edge cases the new approach doesn't cover.
We move the discussion into this PR.
A drip can be optional streamed until a user runs out of funds. These drips are called `defaultDrips`.
They are defined by a start time and an `amtPerSec`.  The `duration=0` indicates the defaultEnd.
After our implementation covers all normally scheduled drips (with a start and duration) we end up with a  leftover `balance` and an array of these defaultDrips.
The leftover balance can be used for defaultDrips.
We need to calculate based on the start dates and amtPerSec the block.timestamp when the user leftover balance will …
=> feat: calc defaultEnd based on unsorted array

package.json, src/Drips.sol, src/test/Drips.t.sol, yarn.lock
Part of https://github.com/radicle-dev/drips-contracts/issues/167 and https://github.com/radicle-dev/drips-contracts/issues/159.
This PR requires an update to prettier, because the old version kept removing the `memory-safe` annotation.
=> Switch default end calculation to binary search 

src/test/Drips.t.sol
Fixes the failing `0x501f37061efca6c824b8a8506d7074552261465b6d8dda8fe1e6354b43e29c53` seed case which crashed https://github.com/radicle-dev/drips-contracts/runs/7424364922#step:9:72.
=> Fix fuzz test handling of drips in the past

README.md, scripts/deploy.sh, src/AddressApp.sol, src/Caller.sol, src/test/Caller.t.sol, src/test/DripsHub.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/192.
Makes https://github.com/radicle-dev/drips-contracts/issues/183 more reasonable.
Makes https://github.com/radicle-dev/drips-contracts/issues/103 more feasible if we choose to go with the `AutomationApp` approach.
It's a minimalistic solution, which seems to still manage to cover all the use cases which we need while staying simple and easily auditable.
It follows ERC-2771, so on the app side all that's needed is deriving from [ERC2771Context](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/ERC2771Context.sol) and then using `_msgSender()` instead of `msg.sender`. See changes made to `AddressApp`.
```ts
// https://codesandbox.io/s/typescript-playground-export-forked-feumq1
import * as …
```
=> Add caller

src/Drips.sol, src/DripsHub.sol, src/Splits.sol, src/test/Drips.t.sol, src/test/DripsHub.t.sol
Functions simulating the result of calling a function don't have a transparent and consistent naming. This PR improves that:
- `receivableDrips` doesn't return the total receivable amount, the result depends on the `maxCycles` parameter provided by the user, `receiveDripsResult` reflects that better.
- `squezableDrips` too doesn't return the total amount, just the result dependent on the provided `dripsHistory`, `squeezeDripsResult` reflects that better.
- `splitResults` is a bad name, the `s` at the end is easy to miss, `splitResult` is easier to handle with eyes.
=> Consistent "*Result" function naming

src/Drips.sol, src/DripsHub.sol, src/Splits.sol, src/test/Drips.t.sol, src/test/Splits.t.sol
This fits better what these constants define: array lengths, which are uint256 anyway. Also fixes the misuse of the term "salt".
=> Widen drips and splits configuratin sizes from uint8 to uint256

Makefile, foundry.toml, test/AddressDriver.t.sol, test/Caller.t.sol, test/Drips.t.sol, test/DripsHub.t.sol, test/ImmutableSplitsDriver.t.sol, test/NFTDriver.t.sol, test/Reserve.t.sol, test/Splits.t.sol
This makes the project structure follow the Foundry's guidelines and moves tests where the tooling actually expects them to be. This also makes https://github.com/radicle-dev/drips-contracts/issues/187 more feasible because clear, understandable for Foundry separation into the source code and the tests allows working around this issue: https://github.com/crytic/slither/issues/1422.
=> Move tests from ./src/test to ./test

src/AddressDriver.sol, src/DripsHub.sol, src/NFTDriver.sol, src/Splits.sol, test/AddressDriver.t.sol, test/DripsHub.t.sol, test/NFTDriver.t.sol, test/Splits.t.sol
The changes:
- `receiveDrips`, `receiveDripsResult` - stop returning `receivableCycles`, because it's easily accessible via `receivableDripsCycles`.
- `splitResults` - return `splitAmt` to consistently match `split` API, even though `splitAmt` could be calculated as `amount - collectableAmt`, but that's confusing.
- `setDrips` - stop returning `newBalance`, because it's easily accessible via `dripsState` along the rest of the state.
=> Clean up returned values

src/Drips.sol, src/DripsHub.sol, test/Drips.t.sol
Clean up the internal API. Remove return values not used in DripsHub and make `_calcMaxEnd` private.
=> Clean up Drips API

foundry.toml, test/Drips.t.sol
Also extend and clean up tests with overlapping cases due to `setDrips` verifying `maxEnd`.
=> Add drips balance fuzz tests

foundry.toml, src/Managed.sol, test/DripsHub.t.sol
Closes #249. Adds the pauser role for DripsHub. The `optimizer_runs` reduction is necessary because the contract was becoming too large to deploy, the performance impact is consistently less than 0.5% for Foundry test runs.
=> Add pauser role

src/NFTDriver.sol, test/NFTDriver.t.sol
OZ stores name and symbol in storage initialized in constructor. Putting the token contract behind a proxy replaces storage with an empty one clearing the token metadata.
=> Fix NFTDriver token metadata

src/DripsHub.sol, test/AddressDriver.t.sol, test/DripsHub.t.sol, test/ImmutableSplitsDriver.t.sol, test/NFTDriver.t.sol
This makes the theoretical attack of draining all driver IDs 4 times slower. Plus it never made sense to register drivers on address `0`.
=> Ban registering drivers for 0 address

src/Drips.sol, src/Managed.sol, src/Splits.sol, test/Drips.t.sol, test/Managed.t.sol, test/Splits.t.sol
The error messages now follow the 32-byte recommendation. Also removes a redundant require statement. It cuts the contract size by about 270 bytes allowing higher optimizer runs.
=> Shorten error messages

foundry.toml, src/Drips.sol, src/DripsHub.sol, src/ImmutableSplitsDriver.sol, src/Splits.sol
This saves quite some gas, depending on the function up to ~15%, and a lot of bytecode, now we're able to increase optimizer runs to almost 12K instead of going down to ~3.5K and still having to shave 30 bytes off. The code is designed and reviewed with making under- and over-flows impossible, so unchecked blocks don't introduce security concerns.
=> Use unchecked blocks where safe

README.md, scripts/deploy.sh, src/Deployer.sol, test/Deployer.t.sol
Makes deployment a single transaction. It requires less than 18M gas, which is fine even on chains with lower gas limits like Optimism (checked on its testnet, it works). Stores the deployment details on chain and updates the JSON. Makes deployment easily repeatable on different chains. Reduces the number of deployment options, now the entire set of contracts is always deployed. Adds tests for the deployment.
=> Add deployer contract

.gitmodules, remappings.txt, src/NFTDriver.sol, src/RepoDriver.sol, test/RepoDriver.t.sol
The production logic is ready to be merged, there are no tests yet, working on them.
Tested out on Goerli (0x45Aa599e4EB38300025eAB83908652bcC61601D4) with GitHub and GitLab, both with the driver covering the fees and the user with `transferAndCall`.
=> Add RepoDriver

test/AddressDriver.t.sol, test/Caller.t.sol, test/NFTDriver.t.sol
Switch the wonky `abi.encodeWithSelector` to a statically typed `abi.encodeCall`. Use metadata generation helpers where possible.
=> Clean up tests

src/Drips.sol, src/ImmutableSplitsDriver.sol, src/Splits.sol, test/Drips.t.sol, test/ImmutableSplitsDriver.t.sol, test/Splits.t.sol, test/dataStore/DripsDataProxy.t.sol
This makes the API simpler and more sane, it requires less effort and gas to parse and validate the calldata.
=> Make the splits weights uint256

src/AddressDriver.sol, src/Drips.sol, src/DriverTransferUtils.sol, src/NFTDriver.sol, src/RepoDriver.sol, src/Streams.sol, src/dataStore/AddressDriverDataProxy.sol, src/dataStore/NFTDriverDataProxy.sol, src/dataStore/RepoDriverDataProxy.sol, test/AddressDriver.t.sol, test/Drips.t.sol, test/DriverTransferUtils.t.sol, test/Giver.t.sol, test/NFTDriver.t.sol, test/RepoDriver.t.sol, test/Streams.t.sol, test/dataStore/AddressDriverDataProxy.t.sol, test/dataStore/DripsDataProxy.t.sol, test/dataStore/NFTDriverDataProxy.t.sol, test/dataStore/RepoDriverDataProxy.t.sol
This makes the calldata simpler by replacing zero-padded 4-byte words with a full word. The API also becomes cleaner by reducing the number of parameters.
=> Make max end hints a custom type

src/Drips.sol, src/Giver.sol, test/Drips.t.sol
This makes the balances type more compatible with the ERC-20 balances.
=> Make Drips balances uint256

test/Streams.t.sol
The scenario checked by the removed fuzz test is already covered by other fuzz tests.
=> Remove PseudoRandomUtils
