- src/Pool.sol
This is the first step toward adding sub-senders. A good side is that because events emission is postponed, now they can be easily deduplicated. Please review thoroughly, dapp tools have no way to test events.
> Deduplicate stream update events 

- src/Pool.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/21
This is the seconds step to introduce sub-senders, refactor the pool to pass around the sender reference and not the ID. It also reintroduces the notion of a sender and receiver address in the API instead of the IDs.
> Pass senders by ref

- src/Pool.sol
- src/test/Pool.t.sol
- src/test/User.t.sol
- src/test/UserUtils.t.sol
The second step toward adding drips. Depends on https://github.com/radicle-dev/radicle-streaming/pull/31
> Drip when collecting

- src/Pool.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/48
> Update sender in memory

- src/Pool.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/49
> Emit stream update events in-place

- src/ERC20Pool.sol
- src/EthPool.sol
- src/Pool.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/50, closes https://github.com/radicle-dev/radicle-streaming/issues/37
> Transfer ERC-20 only once per transaction

- src/DaiPool.sol
- src/ERC20Pool.sol
- src/EthPool.sol
- src/Pool.sol
- src/test/Pool.t.sol
- src/test/User.t.sol
- src/test/UserUtils.t.sol
Closes https://github.com/radicle-dev/radicle-streaming/issues/46.
> Move the whole sender state off-chain

- src/DaiPool.sol
- src/ERC20Pool.sol
- src/EthPool.sol
- src/Pool.sol
- src/test/EthPool.t.sol
- src/test/Pool.t.sol
- src/test/User.t.sol
- src/test/UserUtils.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/58
> Merge topUp and withdraw parameters

- src/DripsHub.sol
- src/ERC20DripsHub.sol
- src/EthDripsHub.sol
- src/test/DripsHubUser.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/64
> Rename receiverAddr and userAddr to user

- src/DripsHub.sol
- src/ERC20DripsHub.sol
- src/EthDripsHub.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUser.t.sol
- src/test/DripsHubUserUtils.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/65
> Rename drips to splits

- src/DaiDripsHub.sol
- src/DripsHub.sol
- src/ERC20DripsHub.sol
- src/EthDripsHub.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUser.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/EthDripsHub.t.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/66
> Rename sending and streams to drips

- src/DaiDripsHub.sol
- src/DripsHub.sol
- src/ERC20DripsHub.sol
- src/EthDripsHub.sol
Depends on https://github.com/radicle-dev/radicle-streaming/pull/67
> Optimize receiver lists validation

- src/DripsHub.sol
- src/ERC20DripsHub.sol
> Switch DripsHub to unstructured storage

- src/ERC20Reserve.sol
- src/test/ERC20Reserve.t.sol
- reserve constructor failed if msg.sender was not owner in setUser method
- added basic tests to reserve
> fix: reserve owner != msg.sender

- src/DripsHub.sol
- src/ManagedDripsHub.sol
Improve separation of concerns by pushing the upgrade-specific logic from DripsHub to ManagedDripsHub.
> Move ERC-1967 drips hub storage logic to ManagedDripsHub

- src/DripsHub.sol
Prepares the storage for the upcoming changes like multi-token, drivers and refactoring into libs.
> Restructure DripsHub storage

- src/DripsHub.sol
- src/ManagedDripsHub.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUser.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/ManagedDripsHub.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/97, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/109.
> Add split and collect

- src/DripsHub.sol
- src/ERC20DripsHub.sol
- src/EthDripsHub.sol
- src/ManagedDripsHub.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUser.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/ManagedDripsHub.t.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/97, blocked by https://github.com/radicle-dev/radicle-drips-hub/pull/110.
> Make collecting for a user callable only by the user

- src/DripsHub.sol
> Make asset in events indexed

- src/test/DripsHub.t.sol
- src/test/DripsHubUser.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/ERC20DripsHub.t.sol
- src/test/ManagedDripsHub.t.sol
- src/test/ManagedDripsHubUser.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/99, blocked by #117.
Clean up test utils in preparation for a switch to an identity contract.
> Prepare tests for AddressId

- src/Drips.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Adds scheduled drips. There are no new tests yet, let's see how this PR goes.
> Add scheduled drips

- src/Reserve.sol
- src/test/Reserve.t.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/101.
> Add reserve plugins

- src/Drips.sol
- src/test/Drips.t.sol
Part of https://github.com/radicle-dev/radicle-drips-hub/issues/84. Fixes a bug which the tests found too!
> Add scheduled drips tests

- src/AddressId.sol
- src/Drips.sol
- src/DripsHub.sol
- src/test/AddressIdUser.t.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/128.
> Store drips last update and balance on-chain

- src/Drips.sol
A tiny improvement reducing storage access hashing and number of passed arguments in Drips.
> Swap drips storage keys to assetId-userId

- src/Drips.sol
- src/Splits.sol
Closes https://github.com/radicle-dev/radicle-drips-hub/issues/84 and https://github.com/radicle-dev/radicle-drips-hub/issues/86.
CC: @gh0stwheel
In this PR the `*ReceiverSeen` events aren't emitted when the user doesn't update their configuration to save gas. This can be further improved by maintaining a global set of already emitted receiver lists. The problem is that the storage cost is high but gas savings aren't guaranteed. If we go in that direction, events handling will also become easier, because there won't be a need to handle multiple copies of the same entries.
> Redesign events around receivers lists

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
- src/test/DripsHubUserUtils.t.sol
- first fuzz test with a random receiver list
- setDrips
- receiveDrips
- all receiver should be able to receive their drips
> test: fuzz drip receivers list

- package.json
- yarn.lock
This is needed so we can use `using ... for ...`.
> Upgrade prettier and solhint to support new Solidity features

- src/AddressApp.sol
- src/AddressId.sol
- src/Drips.sol
- src/DripsHub.sol
- src/Managed.sol
- src/Splits.sol
- src/test/AddressAppUser.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/162. CC: @gh0stwheel
The PR also contains some final cleanups of the v0.1 sub-accounts, it was finally easy to catch the last few mentions of them and even an obsolete test.
> Rename account to app in DripsHub

- README.md
- scripts/deploy.sh
- scripts/local-env.sh
Closes https://github.com/radicle-dev/drips-contracts/issues/161.
A lightly modified script from `radicle-periphery`.
> Add deploy script

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
- src/test/DripsHubUserUtils.t.sol
> Pack the drips parameters

- src/Drips.sol
- Reduce some storage access when checking `nextReceivableCycle`
- Better detection and errors when `amtDeltas` overflows
- More unchecked math
> Small optimizations and better overflow handling in deltas

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/159.
> Add dripping fractions

- src/Drips.sol
- src/DripsHub.sol
- src/Managed.sol
- src/Splits.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/Splits.t.sol
> Turn Drips and Splits into contracts mimicking libraries

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/167
The PR consists of 2 commits, one introducing the actual change and the other just cleaning up the names.
> Make drips durations optional

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
Among other small issues fixes https://github.com/radicle-dev/drips-contracts/issues/194
> Minor code clean-ups

- src/Drips.sol
- src/DripsHub.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/164.
> Add squeezing

- README.md
- scripts/deploy.sh
- src/AddressApp.sol
- src/Managed.sol
- src/Upgradeable.sol
- src/test/DripsHub.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/193
> Add AddressApp upgradeability

- .solhint.json
- Makefile
- foundry.toml
- package.json
- src/AddressApp.sol
- src/Drips.sol
- src/DripsHub.sol
- src/Reserve.sol
- src/Splits.sol
- src/test/AddressAppUser.t.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
- src/test/Reserve.t.sol
- src/test/Splits.t.sol
- yarn.lock
Closes https://github.com/radicle-dev/drips-contracts/issues/188
> Switch to forge fmt

- src/AddressApp.sol
- src/Drips.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
After an update `forge fmt` breaks lines slightly differently
> Run updated forge fmt

- src/AddressApp.sol
- src/DripsHub.sol
- src/test/AddressAppUser.t.sol
- src/test/DripsHub.t.sol
Fixes https://github.com/radicle-dev/drips-contracts/issues/202
> Require authentication when squeezing

- src/AddressApp.sol
- src/DripsHub.sol
- src/Splits.sol
- src/test/AddressAppUser.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/183
> Drop `collectAll` and `collectableAll`

- src/AddressApp.sol
- src/test/AddressAppUser.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/204
> Remove collecting for anybody and accept transfer address in AddressApp

- src/AddressDriver.sol
- src/DripsHub.sol
- src/test/AddressDriverUser.t.sol
- src/test/DripsHub.t.sol
- src/test/DripsHubUserUtils.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/207
> Rename apps to drivers

- README.md
- scripts/deploy.sh
- src/NFTDriver.sol
- src/test/NFTDriver.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/208.
The NFT's token ID is equal to the user ID it controls. The driver is upgradeable.
> Add NFTDriver

- README.md
- scripts/deploy.sh
- src/ImmutableSplitsDriver.sol
- src/test/ImmutableSplitsDriver.t.sol
> Add ImmutableSplitsDriver

- src/AddressDriver.sol
- src/DripsHub.sol
- src/ImmutableSplitsDriver.sol
- src/NFTDriver.sol
- src/test/AddressDriver.t.sol
- src/test/DripsHub.t.sol
- src/test/ImmutableSplitsDriver.t.sol
- src/test/NFTDriver.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/210
> Add metadata

- src/AddressDriver.sol
- src/Drips.sol
- src/DripsHub.sol
- src/NFTDriver.sol
- src/test/AddressDriver.t.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/NFTDriver.t.sol
Implements https://github.com/radicle-dev/drips-contracts/issues/222
> Allow squeezing history before last squeezed

- src/Drips.sol
- src/test/AddressDriver.t.sol
- src/test/Drips.t.sol
- src/test/DripsHub.t.sol
- src/test/NFTDriver.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/225
> Add drip ID

- src/AddressDriver.sol
- src/Drips.sol
- src/DripsHub.sol
- src/NFTDriver.sol
- test/AddressDriver.t.sol
- test/Drips.t.sol
- test/DripsHub.t.sol
- test/NFTDriver.t.sol
There are no tests and no docs yet, that'll be added in the next PRs
> Add end time tips

- src/DripsHub.sol
- src/Splits.sol
- test/Splits.t.sol
Closes https://github.com/radicle-dev/drips-contracts/issues/243
> Stop emitting unneeded Given events

- test/Splits.t.sol
- Switch from passing around the asset ID to a global `asset` variable
- Improve coverage with assertions
> Clean up splits test utils

- src/AddressDriver.sol
- src/Drips.sol
- src/DripsHub.sol
- src/NFTDriver.sol
It's the same docs string in 4 files.
> Add tips docs

- src/Caller.sol
- test/Caller.t.sol
This allows querying for all addresses authorized to `callAs` in Caller, which is important information. Also explicitly reverts when authorizing an authorized address or unauthorizing an unauthorized address, authorizations seem too important to let them be managed carelessly.
> Add allAuthorized to Caller

- test/DripsHub.t.sol
- test/Managed.t.sol
Extracts and cleans up tests for Managed.
> Extract Managed tests

- .gitignore
- certora/SlotTester.sol
- certora/conf/splitsjob.conf
- certora/harness/DripsHubHarness.sol
- certora/harness/DummyERC20A.sol
- certora/harness/DummyERC20B.sol
- certora/harness/DummyERC20Impl.sol
- certora/harness/ReserveHarness.sol
- certora/harness/SplitsHarness.sol
- certora/harness/UpdateReceiverStatesHarness.sol
- certora/scripts/run.sh
- certora/scripts/runBackup.sh
- certora/scripts/runReserve.sh
- certora/scripts/runSlotTester.sh
- certora/scripts/runSplits.sh
- certora/scripts/runSplits2.sh
- certora/specs/DripsHub.spec
- certora/specs/DripsHubBackup.spec
- certora/specs/Reserve.spec
- certora/specs/SlotTester.spec
- certora/specs/Splits.spec
- certora/specs/Splits2.spec
- src/Drips.sol
- src/DripsHub.sol
- src/Managed.sol
- src/Splits.sol
This PR contains all the work done by Certora.
Specifically, the Splits.sol was verified using the script in:
certora/scripts/runSplits.sh
which uses the spec file in:
certora/specs/Splits.spec
For your convenience, instead of running the script above, you could use the new Certora IDE extension for VS Code, with the conf file:
certora/conf/splitsjob.conf
> Certora verification project of Splits.sol

- src/Drips.sol
- src/DripsHub.sol
- test/AddressDriver.t.sol
- test/Drips.t.sol
- test/NFTDriver.t.sol
Ban amtPerSec so low that nothing is dripped.
> Add minAmtPerSec

- scripts/deploy.sh
- src/AddressDriver.sol
- src/Caller.sol
- src/Drips.sol
- src/DripsHub.sol
- src/Managed.sol
- src/NFTDriver.sol
- src/Splits.sol
- test/AddressDriver.t.sol
- test/Drips.t.sol
- test/NFTDriver.t.sol
A handful of small improvements, segregated into docs and code.
> C4 small improvements

- src/Caller.sol
- test/Caller.t.sol
It required some storage structure changes and an extra SLOAD when making any authorization related operations. The strategy is to forget the existing set of authorized addresses and just start using a new clean instance. Clearing an existing set would require few SSTORE operations per unauthorized address, so it could be easily made uncallable by authorizing just a few thousand dummy addresses.
> Add unauthorizeAll to Caller

- src/Caller.sol
It's probably a good thing to at least signal making calls on behalf of others. Plus the current nonce now can be taken straight from events.
> Add more Caller events

- src/Caller.sol
- test/Caller.t.sol
The maximum nonce increase should be sufficient for all practical purposes, but it solves the risk of ever draining nonces.
> Add setNonce to Caller

- src/Managed.sol
- test/Managed.t.sol
This improves discoverability, it's clear what's the current implementation.
> Add implementation to Managed

- src/Managed.sol
- test/Managed.t.sol
This should make it more difficult to accidentally lose admin. This role is so critical that it probably makes sense to do that, all other serious errors and mistakes can be fixed by the admin.
> Make admin change two-step

- src/DriverTransferUtils.sol
- src/NFTDriver.sol
- src/RepoDriver.sol
- test/DriverTransferUtils.t.sol
This encapsulates and deduplicates the non-trivial logic around ERC-20 transfers in drivers.
> Add DriverTransferUtils

- src/Splits.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/33
> Optimize splits order assertion

- src/Splits.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/29 and https://github.com/spearbit-audits/review-drips/issues/32
> Optimize splits counters data types

- src/Splits.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/31
> Optimize splitting algorithm

- src/Splits.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/30
> Optimize iteration

- src/RepoDriver.sol
- test/RepoDriver.t.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/24
> Make updateAnyApiOperator non-pausable

- src/AddressDriver.sol
- src/Drips.sol
- src/DriverTransferUtils.sol
- src/ImmutableSplitsDriver.sol
- src/NFTDriver.sol
- src/RepoDriver.sol
- src/Splits.sol
- src/Streams.sol
- src/dataStore/AddressDriverDataProxy.sol
- src/dataStore/DripsDataProxy.sol
- src/dataStore/NFTDriverDataProxy.sol
- src/dataStore/RepoDriverDataProxy.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/19
> Improve comments

- test/Drips.t.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/18
> Add MAX_TOTAL_BALANCE test

- src/Caller.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/15
> Rename sv to vs

- src/AddressDriver.sol
- src/ImmutableSplitsDriver.sol
- src/NFTDriver.sol
- src/RepoDriver.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/13
> Clean up empty metadata list behavior

- src/AddressDriver.sol
- src/DriverTransferUtils.sol
- src/NFTDriver.sol
- src/RepoDriver.sol
- test/DriverTransferUtils.t.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/12
> Drop _drips() function

- src/Streams.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/11
> Rename currCycleConfigs to lastUpdatedCycleConfigs

- src/NFTDriver.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/10
> Rename onlyHolder to onlyApprovedOrOwner

- src/Splits.sol
Fixes https://github.com/spearbit-audits/review-drips/issues/7
> Emit SplitsSet only if the splits list is new

- .dockerignore
- .github/workflows/publish-docker.yml
- .gitignore
- Dockerfile
- scripts/deploy-docker.sh
- scripts/docker-entrypoint.sh
Adds a Docker setup that builds an image containing an `anvil` testnet with Drips contracts and a test ERC-20 pre-deployed, plus a workflow for publishing it to Dockerhub.
> docker setup
